### ISSUE TITLE
error while calculating commune code for more than one word commune names

### ISSUE THREAD

**Issue by Bohrlotto** [heavybeard/codice-fiscale#1]
Hi,
if I try to calculate the taxcode for a guy born in Castelnuovo di Napoli or in Napoli, the commune code is always the same (F839), that is the one belonging to the former.

**Comment by heavybeard** [comment]
Hi, thanks for your feedback.

Castelnuovo di Napoli is not presente inside [cadastralCode "json"](https://github.com/heavybeard/codice-fiscale/blob/master/source/CodiceFiscale.cadastralCodes.js), maybe it's necessary and update of the list.

If you find an updated list, can you create a PR? (or copy and paste the link here)

I can't looking for it right now

**Comment by Bohrlotto** [comment]
Hi,
I was referring to casalnuovo di napoli (B905). I think that is something related to the regular expression.

**Comment by heavybeard** [comment]
Ok, got it. I checked your commit.

Can you create a PR to update this repo too
