### ISSUE TITLE
Day is not correctly padded when it only has one digit

### ISSUE THREAD

**Issue by Erenor** [heavybeard/codice-fiscale#2]
Replacing line

day = day.toString().substr(day.length - 2, 2);

with 

day = ('00'+day.toString()).substring(day.toString().length);

correctly pads the number and returns a correct Taxcode

**Comment by heavybeard** [comment]
Hi @Erenor ,
thanks for your feedback and your quckly fix. Can you create e PR?

Thanks again

**Comment by Erenor** [comment]
Hello. I tried to push into Development, to create a pull request, but it says that I cannot push: "Authentication failed. You may not have permission to access the repository or the repository may have been archived".

Should I fork to a new branch?

Thank you,
Erenor.

**Comment by heavybeard** [comment]
Yeah, you need to create a fork of my repo to create e PR

**Comment by Erenor** [comment]
PR made :-)

**Comment by heavybeard** [comment]
Merged. Thanks @Erenor !!!
