### ISSUE TITLE
Cadastral Codes

### ISSUE THREAD

**Issue by francescoalcaro** [heavybeard/codice-fiscale#4]
Alcuni comuni come ad esempio Platì presentano un difetto di escape e di conseguenza non viene trovato il codice fiscale di riferimento.

**Comment by heavybeard** [comment]
Can you provide a fix?

**Comment by francescoalcaro** [comment]
I will fix it and upgrade the list.

**Comment by heavybeard** [comment]
Thank you! I appreciate it

**Comment by heavybeard** [comment]
Hi @jarvit ,
cadastral codes updated with Agenzia delle Entrate list
