### ISSUE TITLE
Publish Node package on npm

### ISSUE THREAD

**Issue by zuck** [heavybeard/codice-fiscale#7]
The library seems quite clean and polite, congrats!

Why don't you package and publish it also on npm?

**Comment by heavybeard** [comment]
Yep... I should take some minutes to do it. Thanks for your ping!

**Comment by heavybeard** [comment]
@zuck during publish i saw other libraries like this one, or better then this one. I think it's not useful create a new library on npm with the same purpose

**Comment by heavybeard** [comment]
as reference:
- https://www.npmjs.com/package/codice-fiscale
- https://www.npmjs.com/package/codice-fiscale-js
